export const HANDLE_ADS_CONTAINER = "HANDLE_ADS_CONTAINER";
export const SELECT_ADS_POINT = "SELECT_ADS_POINT";
export const SELECT_ADS_BOARD = "SELECT_ADS_BOARD";
export const SET_ADS_POINTS = "SET_ADS_POINTS";
export const SET_ADS_BOARDS = "SET_ADS_BOARDS";