export const enum EAdsBoardType {
  HIFLEX_BILLBOARD_STAND = 'HIFLEX_BILLBOARD_STAND',
  LED_DISPLAY_STAND = 'LED_DISPLAY_STAND',
  LIGHTBOX_STAND = 'LIGHTBOX_STAND',
  WALL_MOUNTED_HIFLEX_BOARD = 'WALL_MOUNTED_HIFLEX_BOARD',
  WALL_MOUNTED_ELECTRONIC_DISPLAY = 'WALL_MOUNTED_ELECTRONIC_DISPLAY',
  VERTICAL_BANNER_STAND = 'VERTICAL_BANNER_STAND',
  HORIZONTAL_BANNER_STAND = 'HORIZONTAL_BANNER_STAND',
  PANO_STAND_CLUSTER = 'PANO_STAND_CLUSTER',
  WELCOME_GATE = 'WELCOME_GATE',
  SHOPPING_MALL = 'SHOPPING_MALL'
}