export const HANDLE_ADS_CONTAINER = "HANDLE_ADS_CONTAINER";

export const SELECT_ADS_POINT = "SELECT_ADS_POINT";
export const SELECT_ADS_BOARD = "SELECT_ADS_BOARD";
export const FETCH_ADS_POINTS = "FETCH_ADS_POINTS";
export const FETCH_ADS_BOARDS = "FETCH_ADS_BOARDS";