export const HANDLE_ADS_CONTAINER = "HANDLE_ADS_CONTAINER";

export const SELECT_ADS_POINT = "SELECT_ADS_POINT";
export const SELECT_ADS_BOARD = "SELECT_ADS_BOARD";
export const SET_ADS_POINTS = "SET_ADS_POINTS";
export const SET_ADS_BOARDS = "SET_ADS_BOARDS";

export const FETCH_ADS_POINTS_REQUEST = 'FETCH_ADS_POINTS_REQUEST';
export const FETCH_ADS_POINTS_SUCCESS = 'FETCH_ADS_POINTS_SUCCESS';
export const FETCH_ADS_POINTS_FAILURE = 'FETCH_ADS_POINTS_FAILURE';
